DROP DATABASE abc12;
CREATE DATABASE IF NOT EXISTS abc12;
DROP TABLE abc12users;
CREATE TABLE IF NOT EXISTS abc12users(
	USERNAME VARCHAR(100) UNIQUE,
	PASSWORD_HASH VARCHAR(100),
	PHONE VARCHAR(10)
);
USE abc12;
INSERT INTO abc12users(USERNAME, PASSWORD_HASH, PHONE)
VALUES("hoang", "ifjrogo", "123456");
SELECT * FROM abc12users;
SELECT * FROM abc12users WHERE USERNAME=?
